# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MyTinder' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyTinder
  pod 'Firebase/Auth'
  pod 'FirebaseDatabase'
  pod 'FirebaseStorage'
  pod 'SDWebImage', '~>3.8’
end
